services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_BASE_URL: ${API_BASE_URL:-https://api-nexo.stampedev.cloud}
      API_HOST: ${API_HOST:-api-nexo.stampedev.cloud}
    expose:
      - "80"
    restart: unless-stopped
